[theme]
primaryColor="#FFFFFF"   # White text for primary elements
backgroundColor="#000000"  # Black background
secondaryBackgroundColor="#333333"  # Dark grey secondary background
textColor="#FFFFFF"   # White text color
font="sans serif"
